### PR TITLE
fix curl error handler

### PR DESCRIPTION
**Pull request by krichprollsch**
The method `Consumer::handleError` waits an error code and a string (see https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Consumer.php#L93)

This PR fix the bad parameters call and return a real string content as error instead of the curl resource.
Moreover I removed the `Consumer::executePost` which was public (so it's a BC break) to use a loop for retry.

I also introduced a `curl_error` check to handle specific curl errors.

### CODE REVIEW

**Comment by f2prateek** [comment]
hey @krichprollsch thans for the PR! It's not immediately clear to me what the issue was in the old codebase and how this addresses it - could you describe the goal in more detail?

**Comment by krichprollsch** [comment]
The main problems was in the way the `handleError` method was called before [here](https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Consumer/LibCurl.php#L63) and [here](https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Consumer/LibCurl.php#L67):

```php
$this->handleError($ch, $httpResponse);
```

* the order of the parameters is bad, the first parameter must be the error code, the second the message according to the method definition [here](https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Consumer.php#L93)
* `$ch` is not a string, but a libcurl resource. I guess the original idea was to return the body of the request. You can get the body returned by `curl_exec` [1](https://secure.php.net/manual/en/function.curl-exec.php#refsect1-function.curl-exec-returnvalues) (And I forgot to set the option `CURLOPT_RETURNTRANSFER` to curl, I will add it).

To address the second point, I need to get the response code and the body of the request. The method `executePost` can't do that. So I refacto `flushBatch` to replace it by a loop with a retry in case of error.

**Comment by krichprollsch** [comment]
you're welcome @smourph, happy to help you.
maybe @f2prateek could have another look on it?

**Comment by krichprollsch** [comment]
Hello, I have updated my PR to solve the conflicts.
I have just seen #114 fron @kevingilliard which did that work before.

Please @f2prateek can you merge one of these PR soon?
Moreover I think there are so many improvements which can be done in this client: namespaces, psr2 coding style, bumping php version...

**Review by nd4p90x — APPROVED** [review]

**Pull request merged**
