### PR TITLE
Added support for multiple client instances

### PR DESCRIPTION
**Pull request by gmoreira**
I have a use case where I need to operate multiple segment clients in one request thread. Having a static client within the Segment class makes this difficult.

I would like to propose this PR for discussion at the very least.

### CODE REVIEW

**Comment by calvinfo** [comment]
Sorry about the delay here. I like this idea, but I'm unsure what the benefits of this approach are vs just requiring the client directly like we do in the tests and creating new ones there

https://github.com/segmentio/analytics-php/blob/master/test/ConsumerSocketTest.php#L11-L12

**Comment by gmoreira** [comment]
Hi Calvin,

That is a good point and you are very right, I should have noticed that approach earlier.

I guess the only downside in interfacing with the Segment_Client directly would be the loss of all the checking that is performed within each of the Segment methods in terms of assertions and validation.

**Comment by calvinfo** [comment]
You're right, definitely +1 to moving the validation check into the client.

**Comment by ingvar** [comment]
> You're right, definitely +1 to moving the validation check into the client.

What status about this PR?

**Comment by f2prateek** [comment]
I'm going to close this PR as the right solution here is to move the validation into the client.

**Comment by f2prateek** [comment]
(feel free to reopen if the PR gets updated, or link to this if you submit a new PR)

**Pull request closed without merging**
