### PR TITLE
Add namespaces, rename test to tests and add phpunit.xml

### PR DESCRIPTION
**Pull request by vinkla**
Added namespaces and PSR-4 style autoloader. This is similar to #20 but with the new updates.

Added the namespace `Segment`. To fetch the `Segment` object we now have to included it at the top of the document.
```php
<?php

namespace Acme\Services\Segment;

use Segment\Segment;

class SegmentManager
{
	function __construct()
	{
		$this->segment = new Segment();
	}
}
```

What do you guys think? I know this would be appreciated in the PHP community. This update makes it easier for developers to pull in your package into their applications.

### CODE REVIEW

**Comment by asteinlein** [comment]
Yes, pretty please get this merged (should get the tests to pass, though!). We're paying customers and have a Segment class in our app (for segmentation, so it shouldn't be that uncommon a class name) which makes is unable to use this library as-is.

**Comment by vinkla** [comment]
I'll try making the tests pass. Any help would be appreciated!

**Comment by vinkla** [comment]
I'm getting an error in `ConsumerFileTest.php` with the following message:

```bash
1) Segment\Tests\Segment\ConsumerFileTest::testProductionProblems
fopen(/dev/xxxxxxx): failed to open stream: Permission denied
```

Is this the expected behavior and response? What should it return?

**Comment by vinkla** [comment]
Closing this due to lack of interest.

**Pull request closed without merging**
