### PR TITLE
Add namespace and custom consumers

### PR DESCRIPTION
**Pull request by nanodocumet**
# Description
This PR attempts to tackle few things:
1. Adds `Segment` namespace. Similar work done in [#58](https://github.com/segmentio/analytics-php/pull/58l) and [#20](https://github.com/segmentio/analytics-php/pull/20)
2. Adds a `ConsumerInterface` which will allow to create custom consumers
3. ~~Fixes tests typos for `screen`
https://github.com/segmentio/analytics-php/blob/dcbda479fdb9282ab0317dfda0578601725bfa27/test/ConsumerFileTest.php#L69
https://github.com/segmentio/analytics-php/blob/dcbda479fdb9282ab0317dfda0578601725bfa27/test/ConsumerSocketTest.php#L54~~
4. Allows the creation of multiple Analytics instances as proposed in [#59](https://github.com/segmentio/analytics-php/pull/59)
5. Adds some new tests
6. Adds code coverage reports

Most of the work has been pasting existing code to new files with the addition of some other files. In addition new tests cases have been added. Code coverage has been included too.

# Next steps
Before moving forward, wanted to make sure this is a PR that can be considered a candidate to be merged, however, there are still some things that will be needed to be agreed before merging:
1) What version will this PR have?
2) Release section in Makefile will need to be updated
3) HISTORY.md file will need to be updated
4) Some further docblocks need to be added

Let me know what you guys think. Thanks!

### CODE REVIEW

**Comment by f2prateek** [comment]
@nanodocumet thanks for the PR! Unfortunatley this PR is a too broad and tackling too many changes at once. It also makes reviewing significantly more difficult. 

We'd love some of these changes as isolated PRs — in general a PR for every logical change is ideal. The 6 bullet points you listed are each worthy of a PR on their own.

**Comment by nanodocumet** [comment]
@f2prateek Thanks for the response. Sure, I understand. I can start working on those smaller PRs. Let me start with some of the fixes first and then we'll take it from it. Thanks!

**Comment by nanodocumet** [comment]
@f2prateek Created first PR here: (#79)[https://github.com/segmentio/analytics-php/pull/79] to tackle item 5 above.

**Comment by f2prateek** [comment]
Awesome!

Thanks for the PR, really appreciate it! I think after reviewing the changes — we’d love to see the PR split up into the following isolated PRs so we can merge and review them independently (and minimize the risk of breaking existing functionality).

1. Add  `Segment` namespace.
2. Move validation logic into client to add better support for multiple instances.
3. Add consumer interface.
4. Add additional tests and code coverage reports.

(thanks for the already breaking a out #79 into it's own change).

Super excited to see some of these changes being incorporated into the core library.

If possible, I’d like to keep the existing code style and conventions. But I’m open to discuss updating those if you feel strongly about it. Let us know!

Also happy to hop on a call and talk through the changes if you'd like, my number is 203–PRATEEK.

**Pull request closed without merging**
